### ISSUE TITLE
Creating an .srt subtitle file

### ISSUE THREAD

**Issue by christophered** [amsehili/auditok#11]
Hi there,
@amsehili 
I want to create an .srt subtitle file from an audio mp3 file that I have, my goal is to automatically detect the speech regions and create an .srt file with time-stamps and blank transcription, which I will then use to fill the transcription manually.

I have used this command:
```
auditok -e 55 -i interview.mp3 -m 10 --printf "{id}\n{start} --> {end}\nPut some text here...\n" --time-format "%h:%m:%s.%i" -o output.srt
```
the result is:
```
Output #0, srt, to 'c:\users\divana\appdata\local\temp\tmp_s9dvg':
Output file #0 does not contain any stream
```

Though if I dont use the `-o` option, the segments can be viewd in the terminal, but cant export to srt.
Can anyone help in creating a subtitle file .srt with time-stamps
Waiting for your reply

Audi file attached
[interview.zip](https://github.com/amsehili/auditok/files/1212002/interview.zip)

**Comment by amsehili** [comment]
Hello,
here is the command to use, option `-o` is for filename pattern used for output audio segments:
```
auditok -e 55 -i interview.mp3 -m 10 --printf "{id}\n{start} --> {end}\nPut some text here...\n" --time-format "%h:%m:%s.%i" > output.srt
```
cheers
