### ISSUE TITLE
Error when running auditok

### ISSUE THREAD

**Issue by ominds** [amsehili/auditok#14]
This is what I get when I try to run audiotok

ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

I'm on archlinux with python 3.6, any help appreciated!

**Comment by amsehili** [comment]
Hello,
This seems to an issue with your pyaudio installation, please check the the [official documentation](https://people.csail.mit.edu/hubert/pyaudio/) or try reinstalling it.
