### ISSUE TITLE
Splitting audio 

### ISSUE THREAD

**Issue by rrg92** [amsehili/auditok#15]
It possible use auditok to split audio in fixed length, before Silence?

For example:   
```
auditok -n 600 -m 600 -i myFile.wav
```

I want split myFile.wav in up to 600 seconds (10min) of audio. If audio event is greather than 10min, then, it must split most close silence before the 10min boundary. That is possible with current implementation ?

**Comment by amsehili** [comment]
Hello,
I'm not sure I got your question but the command you run would return audio events with a maximum length of 10 minutes. This means that event if your files contains an event 11 min, the previous command will return an event of 10 min followed by another event of 1 min.
