### ISSUE TITLE
splitting the audio with overlaps.

### ISSUE THREAD

**Issue by vaibhav0195** [amsehili/auditok#19]
Hi thanks for this library.
I was wondering if there is a way in which i can split my audio into smaller clips but with adjacent clips having overlapping samples.
Example:
Lets say I have a clip of 1min and it has silences from 10-20sec and then 30-40 secs and my max length of audio is lets say 5 secs. So I was wondering if there is a way in which i can get the splitted audio with duration lets say 1st audio from 0-5 then second audio from 3-8 (overlapping 4and 5 seconds) and so on?

Thanks any help is appreciated.

**Comment by amsehili** [comment]
Hello,
I don't know if you still need this, in case you do, please check the new version on Github (cannot yet be installed via pip but will asap).

The [split](https://github.com/amsehili/auditok/blob/master/auditok/core.py#L30) function returns a generator of [AudioRegion](https://github.com/amsehili/auditok/blob/master/auditok/core.py#L396) that can be sliced manually. You can do something like this:

```python

SLICE_DURATION = 5
OVERLAP = 3

regions = split("audiofile.wav", ...) # set other split parameters
reg = next(regions)
stop = int(reg.duration)
overlapping_regions = [reg[i:i+SLICE_DURATION] for i in range(0, stop, OVERLAP)]

```
