### ISSUE TITLE
Run on-device on Android device

### ISSUE THREAD

**Issue by Nickil21** [amsehili/auditok#26]
I plan to run `auditok` on-device to detect pauses in speech. Currently, it is being handled as an API call (front-end streams the audio via a microphone and sends it to a back-end API which does the segmentation on a real-time basis). 

Is it possible to convert it into a [Tensorflow lite](https://www.tensorflow.org/lite) model sorts for on-device inference, rather than an API call?

**Comment by amsehili** [comment]
Related to #23
