### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by Simpler1** [amsehili/auditok#3]
When I try to run the setup script, I get the following error:

    ~/auditok $ python setup.py install
    Traceback (most recent call last):
      File "setup.py", line 4, in <module>
        from setuptools import setup
    ImportError: No module named setuptools

Where should it be finding this "setuptools" directory/module?

Thanks

**Comment by amsehili** [comment]
You have to install `setuptools` beforehand:

    sudo pip install setuptools

cheers
