### ISSUE TITLE
Is there any citation? I'd like to cite it in our study.

### ISSUE THREAD

**Issue by XingderyFun** [amsehili/auditok#36]
Hello Mr.SEHILI.
This tool is very useful!
I want to cite auditok in our study.
Could you please tell me the citation?
Thanks.

**Comment by amsehili** [comment]
Hello,
Thank you for using this repository, and happy that you found it useful ;)

For citing, you can just use a footnote with a link to the repository. If you want the citation to appear in the references, you can use something like [this](https://academia.stackexchange.com/a/14015) or [this](https://github.com/AASJournals/Tutorials/blob/master/Repositories/CitingRepositories.md). Here's an example of a BibTeX entry:

```
@misc{Sehili_auditok_2021,
  author = {Amine, Sehili},
  title = {auditok: an audio/acoustic activity detection and audio segmentation tool},
  year = {2021},
  publisher = {GitHub},
  url = {\url{https://github.com/amsehili/auditok}},
  version = {0.2.0}
}
```

Cheers.
