### ISSUE TITLE
module 'auditok' has no attribute 'split'

### ISSUE THREAD

**Issue by lfgogogo** [amsehili/auditok#37]
I follow the instructions,and i get an error as the title,why,please help!

**Comment by amsehili** [comment]
Hi,
Which python version are you using? `split` only works with python 3.

**Comment by lfgogogo** [comment]
@amsehili My python version is 3.6.

**Comment by amsehili** [comment]
Could you please share your code and the error message you got?

**Comment by lfgogogo** [comment]
The code is just the same as you offer.And the error message is below.I am running the code on windows os,the / and \ in the message are a little confused.

C:\Users\Administrator\anaconda3\envs\diarization\python.exe D:/chormedl/data_preparation/auditok.py
Traceback (most recent call last):
  File "D:/chormedl/data_preparation/auditok.py", line 1, in <module>
    import auditok
  File "D:\chormedl\data_preparation\auditok.py", line 4, in <module>
    audio_regions = auditok.split(
AttributeError: module 'auditok' has no attribute 'split'

Process finished with exit code 1

**Comment by lfgogogo** [comment]
Thanks a lot,a fool mistake~
