### ISSUE TITLE
Plotting tests failed

### ISSUE THREAD

**Issue by NicolaSmaniotto** [amsehili/auditok#40]
Version: 0.2.0
Command: `python -m unittest discover -v tests/`.
Output: [tests.log](https://github.com/amsehili/auditok/files/6888253/tests.log)
All tests pass with the exception of those in test_plotting.py

**Comment by amsehili** [comment]
Hello,
This is due to matplotlib version mismatch, test images were generated with matplotlib 3.2.1 and plotting tests will only pass with this or older versions (also check [travis config](https://github.com/amsehili/auditok/blob/master/.travis.yml)).
