### ISSUE TITLE
Doubt : format of the output

### ISSUE THREAD

**Issue by Pked01** [amsehili/auditok#42]
Hello
This is not an issue but an doubt
I am using auditok for audio tokenization, 
but i need data in librosa/soundfile format
when i check librosa/sf the data values are in floating points while in auditok they are large numbers
But in both documentation its mentioned that output is timeseries. 
Can you please help me convert one output format to other, or at the least explain what is the format of the output in auditok

**Comment by amsehili** [comment]
Hello,
Librosa converts audio data to a numpy array of floats. In auditok you can use `region.samples` to get audio data as a numpy array (if numpy is installed) or as a standard python array (if numpy is not installed).

**Comment by Pked01** [comment]
> Hello, Librosa converts audio data to a numpy array of floats. In auditok you can use `region.samples` to get audio data as a numpy array (if numpy is installed) or as a standard python array (if numpy is not installed).

**Comment by Pked01** [comment]
> Hello, Librosa converts audio data to a numpy array of floats. In auditok you can use `region.samples` to get audio data as a numpy array (if numpy is installed) or as a standard python array (if numpy is not installed).

actually i tested it
![image](https://user-images.githubusercontent.com/8408124/146813737-e95a340a-7010-41ce-9f5a-e7a62cb89081.png)

when loaded same file give floating point numbers in librosa
whole auditok give  2 separate arrays of channels and sample ..Is there a way to combine output of auditok and get similar array as librosa

**Comment by amsehili** [comment]
Hello,

`librosa.load` has an argument called `mono` which is True by default, meaning that librosa will compute the average of available audio channels and return the result as a 1D array. You can have similar result with auditok like this:

```python
audio = auditok.load("file.wav")
if audio.channels > 1:
    data = np.mean(audio.samples, axis=0)
else:
    data = audio.samples
```

**Comment by Pked01** [comment]
hey 
thanks for responding back..
this is working for me..
only thing there's slight change  in your code...
`audio = auditok.load("file.wav")
if audio.channels > 1:
    data = np.mean(audio.samples, axis=0)/32767
else:
    data = audio.samples/32767`
