### ISSUE TITLE
AudioParameterError

### ISSUE THREAD

**Issue by mmichelli** [amsehili/auditok#48]
auditok.split(
            '/tmp/tmprn08794x.wav'
        )
        
AudioParameterError: The length of audio data must be an integer multiple of `sample_width * channels`

I'm unsure what I should do.

**Comment by amsehili** [comment]
Hello,
This looks like an issue with the header or contents of your audio file, could you try and open it with Audacity?
Also, if possible, could you please share a link to download the file?
