### ISSUE TITLE
on doc : NameError: name 'load' is not defined.

### ISSUE THREAD

**Issue by scenaristeur** [amsehili/auditok#49]
on https://auditok.readthedocs.io/en/latest/examples.html#access-recorded-data-after-split

full_audio = load(rec.data, sr=sr, sw=sw, ch=ch)

should be 
full_audio = auditok.load(rec.data, sr=sr, sw=sw, ch=ch)

**Comment by amsehili** [comment]
Fixed by 4011c403454150c448462a32d5424ed1946170a0.
